// Generated by img_urls.py in ~/tidbits

import aardvarkUrl from "../../images/Aardvark.jpg";
import spinachUrl from "../../images/Spinach.jpg";
import zebraUrl from "../../images/Zebra.jpg";
import snowplowUrl from "../../images/Snowplow.jpg";
import windowsillUrl from "../../images/Windowsill.jpg";
import toddlerUrl from "../../images/Toddler.jpg";
import someoneUrl from "../../images/Someone.jpg";
import nooneUrl from "../../images/Noone.jpg";
import xylophoneUrl from "../../images/Xylophone.jpg";
import mooseUrl from "../../images/Moose.jpg";
import pigeonUrl from "../../images/Pigeon.jpg";
import squidletUrl from "../../images/Squidlet.jpg";

type Images = {
  [person: string]: string;
};

const images: Images = {
  "Aardvark": aardvarkUrl,
  "Spinach": spinachUrl,
  "Zebra": zebraUrl,
  "Snowplow": snowplowUrl,
  "Windowsill": windowsillUrl,
  "Toddler": toddlerUrl,
  "Someone": someoneUrl,
  "Noone": nooneUrl,
  "Xylophone": xylophoneUrl,
  "Moose": mooseUrl,
  "Pigeon": pigeonUrl,
  "Squidlet": squidletUrl
};

export default images;